### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by craigbroadbear** [mike-lischke/rc-converter#1]
Can you please provide some build instructions or link to downloadable binaries?

**Comment by mike-lischke** [comment]
I'm afraid, I don't remember anymore. I published this repo here no so long ago, but wrote it like a decade before. It's pretty simple Java and you should probably start by creating a new Java project and add the files from this repo. You may want to leave out the stuff I wrote as the GUI around the parser.

**Comment by craigbroadbear** [comment]
No problem Mike, I wrote some javascript with a few regex's to extract what
I need from a rc file.

Thanks anyway!

Craig
